config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: "styles#index"
  resources :suppliers
  resources :styles
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture

  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i
  VALID_NAME_REGEX = /\A[ぁ-んァ-ン一-龥]/
  VALID_KANANAME_REGEX = /\A[\p{katakana} ー－&&[^ -~｡-ﾟ]]+\z/
  VALID_EMAIL_REGEX = /\A\S+@\S+\.\S+\z/

  validates :display_name, presence: true
  validates :company_name, presence: true
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true, format: { with: VALID_PASSWORD_REGEX, message: 'must include both letters and numbers'  }
  validates :password, presence: true, format: { with: VALID_PASSWORD_REGEX, message: 'must include both letters and numbers'  }
  validates :family_name_in_charge, presence: true, format: { with: VALID_NAME_REGEX, message: 'must be Full-width characters' }
  validates :first_name_in_charge, presence: true, format: { with: VALID_NAME_REGEX, message: 'must be Full-width characters' }
  validates :kana_family_name_in_charge, presence: true, format: { with: VALID_KANANAME_REGEX, message: 'must be Full-width katakana characters' }
  validates :kana_first_name_in_charge, presence: true, format: { with: VALID_KANANAME_REGEX, message: 'must be Full-width katakana characters' }
  validates :postal_code, presence: true, format: { with: /\A\d{3}[-]\d{4}\z/, message: "invalid: Input Half-width numbers with hyphen"}
  validates :prefecture_id, numericality: { other_than: 0, message: 'must be Selected' }
  validates :city, presence: true
  validates :street_address, presence: true
  validates :phone_number, presence: true, length: { maximum: 11 } 
  validates :mobile_number, length: { maximum: 11 } 
  
  has_many :styles
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  def new
    @supplier = Supplier.new
  end

  def create
    @supplier = Supplier.new(supplier_params)
    if @supplier.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def supplier_params
    params.require(:supplier).permit(
    :display_name, :company_name, :email, :password, :password_confirmation, 
    :family_name_in_charge, :first_name_in_charge, :kana_family_name_in_charge, :kana_first_name_in_charge,
    :postal_code, :prefecture_id, :city, :street_address, :building, :phone_number, :mobile_number, 
    )
  end

end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/suppliers/new.html.erb
<%= render "shared/second-header"%>

<%# 「モデル名」にはUserモデルであれば@userを渡しましょう。「新規登録機能へのパス」は、devise導入後にrails routesを実行してdevise/registrations#createへのパスを確認し、記載してください。 %>
<%= form_with model: @supplier, url: suppliers_path, class: 'registration-main', local: true do |f| %>
<%# //「モデル名」にはUserモデルであれば@userを渡しましょう。「新規登録機能へのパス」は、devise導入後にrails routesを実行してdevise/registrations#createへのパスを確認し、記載してください。 %>
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      出品者情報入力
    </h1>
  </div>

  <%# インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>
  <%# render 'shared/error_messages', model: f.object %>
  <%# //インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">屋号</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :display_name, class:"input-default", id:"nickname", placeholder:"例) Stylus", maxlength:"40" %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">企業・事業者名</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :company_name, class:"input-default", id:"nickname", placeholder:"例) 株式会社スタイラス", maxlength:"40" %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">メールアドレス</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.email_field :email, class:"input-default", id:"email", placeholder:"PCメール", autofocus: true %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">パスワード</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.password_field :password, class:"input-default", id:"password", placeholder:"6文字以上の半角英数字" %>
    <p class='info-text'>※英字と数字の両方を含めて設定してください</p>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">パスワード(確認)</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.password_field :password_confirmation, class:"input-default", id:"password-confirmation", placeholder:"同じパスワードを入力して下さい" %>
  </div>
  <div class="form-group">
    <p class='form-info-header'>
      本人確認
    </p>
    <p class='form-info-text'>
      安心・安全にご利用いただくために、出品者情報の登録にご協力ください。他の出品者様や会員様に公開されることはありません。
    </p>
  <div class="form-group">
    <div class='form-text-wrap'>
    </div>
    <div class='input-birth-wrap'>
      <%#= raw sprintf(
                  f.date_select(
                    :birthday,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 1930,
                    end_year: (Time.now.year - 5),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
    </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">ご担当者名(全角フルネーム)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :family_name_in_charge, class:"input-name", id:"first-name", placeholder:"例) 手須田" %>
      <%= f.text_area :first_name_in_charge, class:"input-name", id:"first-name", placeholder:"例) 一郎" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">ご担当者名(全角カナフルネーム)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :kana_family_name_in_charge, class:"input-name", id:"first-name-kana", placeholder:"例) テスタ" %>
      <%= f.text_area :kana_first_name_in_charge, class:"input-name", id:"first-name-kana", placeholder:"例) イチロウ" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">郵便番号</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :postal_code, class:"input-default", id:"postal_code", placeholder:"例) 551-0001", maxlength:"40" %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">都道府県</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {},  {class:"select-box", id:"item-prefecture"}) %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">市区町村</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :city, class:"input-default", id:"city", placeholder:"例) 渋谷区", maxlength:"40" %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">番地</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :street_address, class:"input-default", id:"street_address", placeholder:"例) 1-1-2", maxlength:"40" %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">建物名・部屋番号(任意）</label>
    </div>
    <%= f.text_area :building, class:"input-default", id:"building", placeholder:"例) 渋谷ビル302", maxlength:"40" %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">電話番号</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :phone_number, class:"input-default", id:"phone_number", placeholder:"例) 0312344321", maxlength:"40" %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">携帯番号（任意）</label>
    </div>
    <%= f.text_area :mobile_number, class:"input-default", id:"shoe_size", placeholder:"例) 09012345678", maxlength:"40" %>
  </div>
    <p class='info-text'>※ 出品者情報は正しく入力してください。出品者登録後、修正するにはお時間を頂く場合があります。</p>
  </div>
  <div class="form-group">
    <h2 class='form-bottom-text'>
      「出品者登録」のボタンを押すことにより、
      <span>利用規約</span>
      <br>に同意したものとみなします
    </h2>
  </div>
  <div class='register-btn'>
    <%= f.submit "出品者登録" ,class:"register-red-btn" %>
  </div>
  <p class='register-info'>本人情報の登録について</p>
</div>
<% end %>

<%= render "shared/second-footer"%>